backend:
    name: bitbucket
    repo: intellidjent/docs-testing
    branch: master

collections:
    - label: "Docs"
      name: "docs"
      folder: "docs"
      create: true
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}

media_folder: "docs/assets"
public_folder: "/images/uploads"
